#!/usr/bin/env node
/**
 * SEO build helper.
 *
 *   node scripts/seo-build.js
 *
 * What it does:
 *   1. Reads data/packages.json
 *   2. Regenerates sitemap.xml so every visible package + every static
 *      page is included with a fresh `<lastmod>` date (today).
 *
 * Run this after editing packages or static pages so search engines
 * pick up your changes faster. Safe to run as part of the npm `build`
 * script — just appends an `&& node scripts/seo-build.js` to the
 * existing build pipeline.
 */
'use strict';

const fs    = require('fs');
const path  = require('path');
const https = require('https');

const ROOT      = path.resolve(__dirname, '..');
const PKG_FILE  = path.join(ROOT, 'data', 'packages.json');
const OUT_FILE  = path.join(ROOT, 'sitemap.xml');
const SITE      = 'https://andamanvoyages.in';

const today = new Date().toISOString().split('T')[0];

// Static pages — use the clean canonical URLs (no .html), matching the
// canonical tags inside each HTML page. These are the URLs Google should
// index, NOT the .html variants (which would create duplicate-content).
const STATIC_URLS = [
    { loc: '/',         priority: '1.0', changefreq: 'weekly',  image: 'images/beach1.jpg', imageTitle: 'Andaman Holiday Packages' },
    { loc: '/flights',  priority: '0.9', changefreq: 'weekly',  image: 'images/neil2.jpg',  imageTitle: 'Flights to Andaman' },
    { loc: '/cabs',     priority: '0.9', changefreq: 'weekly',  image: 'images/beach1.jpg', imageTitle: 'Andaman Cab Hire' },
    { loc: '/gallery',  priority: '0.8', changefreq: 'weekly',  image: 'images/beach2.jpg', imageTitle: 'Andaman Photo Gallery' },
    { loc: '/about',    priority: '0.6', changefreq: 'monthly', image: 'images/logo.png',   imageTitle: 'About Bharat Transport and Tourism' },
    { loc: '/privacy',  priority: '0.3', changefreq: 'yearly' },
    { loc: '/terms',    priority: '0.3', changefreq: 'yearly' }
];

// ── Load packages ─────────────────────────────────────────────
let packages = [];
try {
    packages = JSON.parse(fs.readFileSync(PKG_FILE, 'utf8')) || [];
    if (!Array.isArray(packages)) packages = [];
} catch (err) {
    console.warn('[seo-build] Could not read', PKG_FILE, '— using defaults');
    packages = [
        { id: 'budget',    name: 'Budget Andaman Escape',  image: 'images/beach1.jpg' },
        { id: 'standard',  name: 'Standard Andaman Bliss', image: 'images/beach2.jpg' },
        { id: 'luxury',    name: 'Luxury Andaman Retreat', image: 'images/beach3.jpg' },
        { id: 'honeymoon', name: 'Honeymoon Paradise',     image: 'images/beach4.jpg' }
    ];
}

// Filter: visible-only and skip the test/demo packages
const visiblePackages = packages.filter(p =>
    p && p.id &&
    p.id !== 'test' &&
    p.visible !== false
);

// ── Build sitemap ─────────────────────────────────────────────
function escXml(s) {
    return String(s == null ? '' : s)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function urlBlock(entry) {
    const lines = [];
    lines.push('    <url>');
    lines.push(`        <loc>${SITE}${entry.loc}</loc>`);
    lines.push(`        <lastmod>${today}</lastmod>`);
    if (entry.changefreq) lines.push(`        <changefreq>${entry.changefreq}</changefreq>`);
    if (entry.priority)   lines.push(`        <priority>${entry.priority}</priority>`);
    if (entry.image) {
        lines.push('        <image:image>');
        lines.push(`            <image:loc>${SITE}/${entry.image.replace(/^\/+/, '')}</image:loc>`);
        if (entry.imageTitle) {
            lines.push(`            <image:title>${escXml(entry.imageTitle)}</image:title>`);
        }
        lines.push('        </image:image>');
    }
    lines.push('    </url>');
    return lines.join('\n');
}

const blocks = [];

// 1. Static
STATIC_URLS.forEach(s => blocks.push(urlBlock(s)));

// 2. Packages — only include the clean canonical URL.
// We deliberately do NOT add the .html variant: every package.html page
// already has <link rel="canonical" href=".../package?id=..."> pointing
// at the clean URL, so adding both would create duplicate-content noise.
visiblePackages.forEach(p => {
    blocks.push(urlBlock({
        loc:        `/package?id=${encodeURIComponent(p.id)}`,
        priority:   '0.9',
        changefreq: 'weekly',
        image:      p.image || 'images/beach1.jpg',
        imageTitle: p.name || 'Andaman Tour Package'
    }));
});

const xml =
    `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

    <!-- Auto-generated by scripts/seo-build.js on ${today} -->

${blocks.join('\n\n')}

</urlset>
`;

fs.writeFileSync(OUT_FILE, xml, 'utf8');
console.log(`[seo-build] sitemap.xml regenerated with ${STATIC_URLS.length + visiblePackages.length} URLs (${visiblePackages.length} packages + ${STATIC_URLS.length} static)`);

// ─────────────────────────────────────────────────────────────────────
// IndexNow ping (Bing, Yandex, Seznam, Naver) — instant discovery without
// waiting for the next crawl. Google does NOT use IndexNow but it doesn't
// hurt; for Google we rely on the sitemap submitted in Search Console.
//
// 1. Place a key file at /<KEY>.txt in the repo root (the file's content
//    must be exactly the same key).
// 2. Set INDEXNOW_KEY env var to that key value, OR drop a file named
//    `.indexnow-key` in the repo root with the key on a single line.
// 3. The script then POSTs the full URL list to api.indexnow.org.
//
// Skipped silently when no key is configured.
// ─────────────────────────────────────────────────────────────────────
function loadIndexNowKey() {
    if (process.env.INDEXNOW_KEY) return String(process.env.INDEXNOW_KEY).trim();
    try {
        const k = fs.readFileSync(path.join(ROOT, '.indexnow-key'), 'utf8').trim();
        if (k) return k;
    } catch (_) {}
    return null;
}

function pingIndexNow(key) {
    const urlList = [
        ...STATIC_URLS.map(s => SITE + s.loc),
        ...visiblePackages.map(p => `${SITE}/package?id=${encodeURIComponent(p.id)}`)
    ];
    const payload = JSON.stringify({
        host: 'andamanvoyages.in',
        key,
        keyLocation: `${SITE}/${key}.txt`,
        urlList
    });
    const req = https.request({
        hostname: 'api.indexnow.org',
        path: '/IndexNow',
        method: 'POST',
        headers: {
            'Content-Type': 'application/json; charset=utf-8',
            'Content-Length': Buffer.byteLength(payload)
        }
    }, res => {
        console.log(`[seo-build] IndexNow ping → HTTP ${res.statusCode} for ${urlList.length} URLs`);
        res.resume();
    });
    req.on('error', err => console.warn('[seo-build] IndexNow ping failed:', err.message));
    req.write(payload);
    req.end();
}

const indexNowKey = loadIndexNowKey();
if (indexNowKey) {
    pingIndexNow(indexNowKey);
} else {
    console.log('[seo-build] (skipping IndexNow ping — no INDEXNOW_KEY env or .indexnow-key file)');
}

// ─────────────────────────────────────────────────────────────────────
// Google sitemap ping (legacy but still works)
// ─────────────────────────────────────────────────────────────────────
function pingGoogleSitemap() {
    const sm = encodeURIComponent(`${SITE}/sitemap.xml`);
    https.get(`https://www.google.com/ping?sitemap=${sm}`, res => {
        console.log(`[seo-build] Google sitemap ping → HTTP ${res.statusCode}`);
        res.resume();
    }).on('error', err => console.warn('[seo-build] Google ping failed:', err.message));
}
if (process.env.PING_GOOGLE === '1' || process.env.SEO_PING === '1') {
    pingGoogleSitemap();
}
