#!/usr/bin/env node
/**
 * SEO build helper.
 *
 *   node scripts/seo-build.js
 *
 * What it does:
 *   1. Reads data/packages.json
 *   2. Regenerates sitemap.xml so every visible package + every static
 *      page is included with a fresh `<lastmod>` date (today).
 *
 * Run this after editing packages or static pages so search engines
 * pick up your changes faster. Safe to run as part of the npm `build`
 * script — just appends an `&& node scripts/seo-build.js` to the
 * existing build pipeline.
 */
'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT      = path.resolve(__dirname, '..');
const PKG_FILE  = path.join(ROOT, 'data', 'packages.json');
const OUT_FILE  = path.join(ROOT, 'sitemap.xml');
const SITE      = 'https://andamanvoyages.in';

const today = new Date().toISOString().split('T')[0];

// Static pages that should always appear in the sitemap with their
// crawl priority + change frequency.
const STATIC_URLS = [
    { loc: '/',             priority: '1.0', changefreq: 'weekly',  image: 'images/beach1.jpg', imageTitle: 'Andaman Holiday Packages' },
    { loc: '/gallery.html', priority: '0.8', changefreq: 'weekly',  image: 'images/beach2.jpg', imageTitle: 'Andaman Photo Gallery' },
    { loc: '/about.html',   priority: '0.6', changefreq: 'monthly', image: 'images/logo.png',   imageTitle: 'About Bharat Tours and Travels' },
    { loc: '/privacy.html', priority: '0.3', changefreq: 'yearly' },
    { loc: '/terms.html',   priority: '0.3', changefreq: 'yearly' }
];

// ── Load packages ─────────────────────────────────────────────
let packages = [];
try {
    packages = JSON.parse(fs.readFileSync(PKG_FILE, 'utf8')) || [];
    if (!Array.isArray(packages)) packages = [];
} catch (err) {
    console.warn('[seo-build] Could not read', PKG_FILE, '— using defaults');
    packages = [
        { id: 'budget',    name: 'Budget Andaman Escape',  image: 'images/beach1.jpg' },
        { id: 'standard',  name: 'Standard Andaman Bliss', image: 'images/beach2.jpg' },
        { id: 'luxury',    name: 'Luxury Andaman Retreat', image: 'images/beach3.jpg' },
        { id: 'honeymoon', name: 'Honeymoon Paradise',     image: 'images/beach4.jpg' }
    ];
}

// Filter: visible-only and skip the test/demo packages
const visiblePackages = packages.filter(p =>
    p && p.id &&
    p.id !== 'test' &&
    p.visible !== false
);

// ── Build sitemap ─────────────────────────────────────────────
function escXml(s) {
    return String(s == null ? '' : s)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function urlBlock(entry) {
    const lines = [];
    lines.push('    <url>');
    lines.push(`        <loc>${SITE}${entry.loc}</loc>`);
    lines.push(`        <lastmod>${today}</lastmod>`);
    if (entry.changefreq) lines.push(`        <changefreq>${entry.changefreq}</changefreq>`);
    if (entry.priority)   lines.push(`        <priority>${entry.priority}</priority>`);
    if (entry.image) {
        lines.push('        <image:image>');
        lines.push(`            <image:loc>${SITE}/${entry.image.replace(/^\/+/, '')}</image:loc>`);
        if (entry.imageTitle) {
            lines.push(`            <image:title>${escXml(entry.imageTitle)}</image:title>`);
        }
        lines.push('        </image:image>');
    }
    lines.push('    </url>');
    return lines.join('\n');
}

const blocks = [];

// 1. Static
STATIC_URLS.forEach(s => blocks.push(urlBlock(s)));

// 2. Packages
visiblePackages.forEach(p => {
    blocks.push(urlBlock({
        loc:        `/package?id=${encodeURIComponent(p.id)}`,
        priority:   '0.9',
        changefreq: 'weekly',
        image:      p.image || 'images/beach1.jpg',
        imageTitle: p.name || 'Andaman Tour Package'
    }));
    // Also include the .html variant so direct hits still get indexed
    blocks.push(urlBlock({
        loc:        `/package.html?id=${encodeURIComponent(p.id)}`,
        priority:   '0.8',
        changefreq: 'weekly'
    }));
});

const xml =
    `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

    <!-- Auto-generated by scripts/seo-build.js on ${today} -->

${blocks.join('\n\n')}

</urlset>
`;

fs.writeFileSync(OUT_FILE, xml, 'utf8');
console.log(`[seo-build] sitemap.xml regenerated with ${STATIC_URLS.length + visiblePackages.length * 2} URLs (${visiblePackages.length} packages × 2 variants + ${STATIC_URLS.length} static)`);